/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filtrasi.pasien.igd;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class RSJahan extends javax.swing.JFrame {

    /**
     * Creates new form RSJahan
     */
    public RSJahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pria = new javax.swing.JRadioButton();
        Wanita = new javax.swing.JRadioButton();
        Demam = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        SesakNafas = new javax.swing.JCheckBox();
        Batuk = new javax.swing.JCheckBox();
        Pilek = new javax.swing.JCheckBox();
        SakitTenggorokkan = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        NamaPasien = new javax.swing.JTextField();
        NomorBPJS = new javax.swing.JTextField();
        SuhuTubuh = new javax.swing.JTextField();
        Lanjut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Keluhanlain = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PASIEN IGD RS JAHAN");

        jLabel2.setText("Nama Pasien");

        jLabel3.setText("Nomor BPJS");

        jLabel4.setText("Masukkan Suhu Tubuh Anda");

        jLabel5.setText("Jenis Kelamin");

        Pria.setText("Pria");
        Pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriaActionPerformed(evt);
            }
        });

        Wanita.setText("Wanita");
        Wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WanitaActionPerformed(evt);
            }
        });

        Demam.setText("Demam");

        jLabel6.setText("Pilih gejala yang di alami");

        SesakNafas.setText("Sesak Nafas");

        Batuk.setText("Batuk");

        Pilek.setText("Pilek");

        SakitTenggorokkan.setText("Sakit Tenggorokkan");
        SakitTenggorokkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SakitTenggorokkanActionPerformed(evt);
            }
        });

        jLabel7.setText("Keluhan Lain");

        Lanjut.setText("Simpan");
        Lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LanjutActionPerformed(evt);
            }
        });

        Keluhanlain.setColumns(20);
        Keluhanlain.setRows(5);
        jScrollPane1.setViewportView(Keluhanlain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(SesakNafas)
                                    .addGap(18, 18, 18)
                                    .addComponent(Pilek)
                                    .addGap(341, 341, 341))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(314, 314, 314)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NamaPasien)
                                        .addComponent(NomorBPJS)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(181, 181, 181)
                                    .addComponent(jScrollPane1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Demam)
                                            .addGap(18, 18, 18)
                                            .addComponent(Batuk)
                                            .addGap(18, 18, 18)
                                            .addComponent(SakitTenggorokkan)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SuhuTubuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Pria)
                                            .addGap(18, 18, 18)
                                            .addComponent(Wanita)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(Lanjut)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(NomorBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SuhuTubuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Pria)
                    .addComponent(Wanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Demam)
                    .addComponent(Batuk)
                    .addComponent(SakitTenggorokkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SesakNafas)
                    .addComponent(Pilek))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(Lanjut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SakitTenggorokkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SakitTenggorokkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SakitTenggorokkanActionPerformed

    private void LanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LanjutActionPerformed
        // TODO add your handling code here:
        int i=0;
        String kelamin = "-";
        String ruangan = "-";
        
        String nama = NamaPasien.getText();
        String bpjs = NomorBPJS.getText();
        int suhu = Integer.parseInt(SuhuTubuh.getText());
        if(Pria.isSelected()){
            kelamin = "Pria";
        } else if (Wanita.isSelected()){
            kelamin = "wanita";
        }
        if(Demam.isSelected()){
            i=i+1;
        }else if(Batuk.isSelected()){
            i=i+1;
        }else if(SakitTenggorokkan.isSelected()){
            i=i+1;
        }else if(SesakNafas.isSelected()){
            i=i+1;
        }else if(Pilek.isSelected()){
            i=i+1;
        }
        
        if (i>=3 && suhu >=37){
            ruangan = "B";
        } else {
            ruangan = "A";
        }
        
        String KeluhanLain = Keluhanlain.getText();
        
        RuangTungguPasien.tambah(new Object[]{
            nama,bpjs,KeluhanLain,ruangan
        });
        this.setVisible(false);
        JOptionPane.showMessageDialog(null,"Pasien Berhasil di Tambahkan!");
    }//GEN-LAST:event_LanjutActionPerformed

    private void PriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriaActionPerformed
        // TODO add your handling code here:
        Wanita.setSelected(false);
    }//GEN-LAST:event_PriaActionPerformed

    private void WanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WanitaActionPerformed
        // TODO add your handling code here:
        Pria.setSelected(false);
    }//GEN-LAST:event_WanitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSJahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSJahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSJahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSJahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSJahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Batuk;
    private javax.swing.JCheckBox Demam;
    private javax.swing.JTextArea Keluhanlain;
    private javax.swing.JButton Lanjut;
    private javax.swing.JTextField NamaPasien;
    private javax.swing.JTextField NomorBPJS;
    private javax.swing.JCheckBox Pilek;
    private javax.swing.JRadioButton Pria;
    private javax.swing.JCheckBox SakitTenggorokkan;
    private javax.swing.JCheckBox SesakNafas;
    private javax.swing.JTextField SuhuTubuh;
    private javax.swing.JRadioButton Wanita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    


}
